FROM python:3.12-slim

WORKDIR app

COPY src server.py pyproject.toml poetry.lock .flake8 ./

RUN pip install --upgrade pip \
    && pip install pip install poetry \
    && poetry install --no-root


ENTRYPOINT ["poetry", "run", "python", "server.py"]