FROM python:3.12-slim

WORKDIR /app

# Copy the entire backend directory structure
COPY backend/src ./src
COPY backend/server.py backend/pyproject.toml backend/poetry.lock backend/.flake8 ./

RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry install --no-root


ENTRYPOINT ["poetry", "run", "python", "server.py"]
