"""add video_type model

Revision ID: 31cbca9f2d64
Revises: e1f0853ee7f4
Create Date: 2026-02-19 13:42:20.306278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cbca9f2d64'
down_revision: Union[str, Sequence[str], None] = 'e1f0853ee7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('planes', sa.Column('video_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planes', 'video_type',
                          ['video_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planes', type_='foreignkey')
    op.drop_column('planes', 'video_type_id')
    op.drop_table('video_type')
    # ### end Alembic commands ###
