"""Add squads table

Revision ID: 592a26e3160f
Revises: f483e358fde5
Create Date: 2026-01-21 15:20:26.811040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592a26e3160f'
down_revision: Union[str, Sequence[str], None] = 'f483e358fde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('device', sa.Integer(), nullable=True)
    )
    op.create_foreign_key('fk_squads_device_planes',
                          'squads',
                          'planes',
                          ['device'],
                          ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_squads_device_planes', 'squads', type_='foreignkey')
    op.drop_table('squads')
    # ### end Alembic commands ###
