"""add unique constraint to plane name

Revision ID: 681f11045f2b
Revises: c273e12d524b
Create Date: 2026-01-22 10:48:17.205859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681f11045f2b'
down_revision: Union[str, Sequence[str], None] = 'c273e12d524b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Cleanup duplicates before adding unique constraint
    op.execute("""
        DELETE FROM planes
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY name ORDER BY id) AS row_num
                FROM planes
                WHERE name IS NOT NULL
            ) t
            WHERE t.row_num > 1
        )
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'planes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planes', type_='unique')
    # ### end Alembic commands ###
