"""Add image field to plane model

Revision ID: c273e12d524b
Revises: 592a26e3160f
Create Date: 2026-01-22 10:34:55.597214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c273e12d524b'
down_revision: Union[str, Sequence[str], None] = '592a26e3160f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planes', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planes', 'image_url')
    # ### end Alembic commands ###
