"""Add relations to the planes and squads models

Revision ID: e1f0853ee7f4
Revises: 681f11045f2b
Create Date: 2026-02-19 12:27:45.955894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f0853ee7f4'
down_revision: Union[str, Sequence[str], None] = '681f11045f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squad_plane_association',
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('plane_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plane_id'], ['planes.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('squad_id', 'plane_id')
    )
    op.drop_constraint('fk_squads_device_planes', 'squads', type_='foreignkey')
    op.drop_column('squads', 'device')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squads', sa.Column('device', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_squads_device_planes', 'squads', 'planes', ['device'], ['id'])
    op.drop_table('squad_plane_association')
    # ### end Alembic commands ###
