"""add unique constraint to communication_type name

Revision ID: f483e358fde5
Revises: e7cc38e77eec
Create Date: 2026-01-21 14:53:57.910917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f483e358fde5'
down_revision: Union[str, Sequence[str], None] = 'e7cc38e77eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'communication_type', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communication_type', type_='unique')
    # ### end Alembic commands ###
